language: go

go:
  - "1.10"

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
  - cd cmd/blog-generator && go build

after_success:
  - bash <(curl -s https://codecov.io/bash)